# Generated by Django 3.2.5 on 2021-07-22 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('original_language', models.CharField(max_length=100)),
                ('original_title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('popularity', models.IntegerField()),
                ('poster_path', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=200)),
                ('vote_average', models.IntegerField()),
                ('date_added', models.DateTimeField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix.userprofile')),
            ],
        ),
    ]
