# Generated by Django 3.2.5 on 2021-07-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0004_playlist_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='popularity',
            field=models.FloatField(),
        ),
    ]
