# Generated by Django 3.2.5 on 2021-07-22 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0006_alter_playlist_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='original_language',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='original_title',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='poster_path',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='vote_average',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='vote_count',
        ),
    ]
