# Generated by Django 3.2.5 on 2021-07-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0007_auto_20210723_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='original_language',
            field=models.CharField(default='Nadia', max_length=100),
            preserve_default=False,
        ),
    ]
