# Generated by Django 3.2.5 on 2021-07-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0008_playlist_original_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='original_title',
            field=models.CharField(default='Nadia', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='overview',
            field=models.TextField(default='Nadia'),
            preserve_default=False,
        ),
    ]
