# Generated by Django 3.2.5 on 2021-07-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0009_auto_20210723_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='popularity',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
