# Generated by Django 3.2.5 on 2021-07-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0010_playlist_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='popularity',
            field=models.FloatField(),
        ),
    ]
