# Generated by Django 3.2.5 on 2021-07-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0012_auto_20210723_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='vote_average',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
