# Generated by Django 3.2.5 on 2021-07-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0013_auto_20210723_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='vote_average',
            field=models.FloatField(),
        ),
    ]
